//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace autodbModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class autodbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new autodbEntities object using the connection string found in the 'autodbEntities' section of the application configuration file.
        /// </summary>
        public autodbEntities() : base("name=autodbEntities", "autodbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autodbEntities object.
        /// </summary>
        public autodbEntities(string connectionString) : base(connectionString, "autodbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autodbEntities object.
        /// </summary>
        public autodbEntities(EntityConnection connection) : base(connection, "autodbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<autott> wanhatautot
        {
            get
            {
                if ((_wanhatautot == null))
                {
                    _wanhatautot = base.CreateObjectSet<autott>("wanhatautot");
                }
                return _wanhatautot;
            }
        }
        private ObjectSet<autott> _wanhatautot;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the wanhatautot EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowanhatautot(autott autott)
        {
            base.AddObject("wanhatautot", autott);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autodbModel", Name="autott")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class autott : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new autott object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static autott Createautott(global::System.Int32 id)
        {
            autott autott = new autott();
            autott.id = id;
            return autott;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rekkari
        {
            get
            {
                return _rekkari;
            }
            set
            {
                OnrekkariChanging(value);
                ReportPropertyChanging("rekkari");
                _rekkari = StructuralObject.SetValidValue(value, true, "rekkari");
                ReportPropertyChanged("rekkari");
                OnrekkariChanged();
            }
        }
        private global::System.String _rekkari;
        partial void OnrekkariChanging(global::System.String value);
        partial void OnrekkariChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String merkki
        {
            get
            {
                return _merkki;
            }
            set
            {
                OnmerkkiChanging(value);
                ReportPropertyChanging("merkki");
                _merkki = StructuralObject.SetValidValue(value, true, "merkki");
                ReportPropertyChanged("merkki");
                OnmerkkiChanged();
            }
        }
        private global::System.String _merkki;
        partial void OnmerkkiChanging(global::System.String value);
        partial void OnmerkkiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String malli
        {
            get
            {
                return _malli;
            }
            set
            {
                OnmalliChanging(value);
                ReportPropertyChanging("malli");
                _malli = StructuralObject.SetValidValue(value, true, "malli");
                ReportPropertyChanged("malli");
                OnmalliChanged();
            }
        }
        private global::System.String _malli;
        partial void OnmalliChanging(global::System.String value);
        partial void OnmalliChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vm
        {
            get
            {
                return _vm;
            }
            set
            {
                OnvmChanging(value);
                ReportPropertyChanging("vm");
                _vm = StructuralObject.SetValidValue(value, "vm");
                ReportPropertyChanged("vm");
                OnvmChanged();
            }
        }
        private Nullable<global::System.Int32> _vm;
        partial void OnvmChanging(Nullable<global::System.Int32> value);
        partial void OnvmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> myyntihinta
        {
            get
            {
                return _myyntihinta;
            }
            set
            {
                OnmyyntihintaChanging(value);
                ReportPropertyChanging("myyntihinta");
                _myyntihinta = StructuralObject.SetValidValue(value, "myyntihinta");
                ReportPropertyChanged("myyntihinta");
                OnmyyntihintaChanged();
            }
        }
        private Nullable<global::System.Int32> _myyntihinta;
        partial void OnmyyntihintaChanging(Nullable<global::System.Int32> value);
        partial void OnmyyntihintaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sisaanostohinta
        {
            get
            {
                return _sisaanostohinta;
            }
            set
            {
                OnsisaanostohintaChanging(value);
                ReportPropertyChanging("sisaanostohinta");
                _sisaanostohinta = StructuralObject.SetValidValue(value, "sisaanostohinta");
                ReportPropertyChanged("sisaanostohinta");
                OnsisaanostohintaChanged();
            }
        }
        private Nullable<global::System.Int32> _sisaanostohinta;
        partial void OnsisaanostohintaChanging(Nullable<global::System.Int32> value);
        partial void OnsisaanostohintaChanged();

        #endregion

    }

    #endregion

}
