<%@ Page Title="" Language="C#" MasterPageFile="~/Tehtava-3/treemaster.master" AutoEventWireup="true" CodeFile="G2700_Treeview.aspx.cs" Inherits="Tehtava_3_G2700_Treeview" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <div>
        
        <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" DataSourceID="xmlLeffat">
            <DataBindings>
                <asp:TreeNodeBinding DataMember="leffat" Text="Movies" Value="Movie Information" />
                <asp:TreeNodeBinding DataMember="genre" TextField="name" />
                <asp:TreeNodeBinding DataMember="name" TextField="#InnerText" />
            </DataBindings>
        </asp:TreeView>
        <asp:XmlDataSource ID="xmlLeffat" runat="server" DataFile="~/leffat.xml"></asp:XmlDataSource>
        
        </div>
</asp:Content>

